# Generated by Django 5.0.1 on 2024-02-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lectures', '0001_initial'),
        ('app_notebooks', '0004_notebook_image_relative_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lecture_relative_url', models.CharField(blank=True, max_length=100, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='app_notebooks.notebook')),
            ],
        ),
        migrations.DeleteModel(
            name='Lectures',
        ),
    ]
