# Generated by Django 5.0.1 on 2024-02-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebooks', '0004_notebook_image_relative_url'),
        ('app_users', '0002_userfavouritenotebook_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfavouritenotebook',
            constraint=models.UniqueConstraint(fields=('user', 'notebook'), name='unique_user_notebook'),
        ),
    ]
